<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6mUx4iF\App_KernelLocalDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6mUx4iF/App_KernelLocalDebugContainer.php') {
    touch(__DIR__.'/Container6mUx4iF.legacy');

    return;
}

if (!\class_exists(App_KernelLocalDebugContainer::class, false)) {
    \class_alias(\Container6mUx4iF\App_KernelLocalDebugContainer::class, App_KernelLocalDebugContainer::class, false);
}

return new \Container6mUx4iF\App_KernelLocalDebugContainer([
    'container.build_hash' => '6mUx4iF',
    'container.build_id' => '59481810',
    'container.build_time' => 1678221152,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6mUx4iF');
