<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZBbScVL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZBbScVL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZBbScVL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZBbScVL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZBbScVL\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZBbScVL',
    'container.build_id' => 'f417d264',
    'container.build_time' => 1679610102,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZBbScVL');
